project/Dependencies.scala

I upgraded skafka in #442 , but forgot to update org.apache.kafka itself. This results in kafka 2.8 being selected when kafka-journal is used as a dependency.

Update kafka to 3.4.0

---

eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/PointerStatements.scala
eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/ReplicatedCassandra.scala
tests/src/test/scala/com/evolutiongaming/kafka/journal/replicator/ReplicatorIntSpec.scala

- use `pointer2` in `ReplicatedCassandra` as the first target of inserts and updates
- make `PointerStatements#Insert` sequential
- fix a flaky test in `ReplicatorIntSpec`

Insert pointers sequentially in the correct order; fix test assert

---

eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/PointerStatements.scala
eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/ReplicatedCassandra.scala
tests/src/test/scala/com/evolutiongaming/kafka/journal/replicator/ReplicatorIntSpec.scala

- use `pointer2` in `ReplicatedCassandra` as the first target of inserts and updates
- make `PointerStatements#Insert` sequential
- fix a flaky test in `ReplicatorIntSpec`
Backport of https://github.com/evolution-gaming/kafka-journal/pull/481

Insert pointers sequentially in the correct order; fix test assert [CE2]

---

build.sbt
journal/src/main/scala/com/evolutiongaming/kafka/journal/HeadCacheMetrics.scala
project/Dependencies.scala

[CE2] Remove dependency to com.evolutiongaming:scache

---

eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/EventualCassandra.scala
eventual-cassandra/src/test/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/EventualCassandraTest.scala
journal/src/main/scala/com/evolutiongaming/kafka/journal/Journals.scala
journal/src/test/scala/com/evolutiongaming/kafka/journal/JournalSpec.scala
tests/src/test/scala/com/evolutiongaming/kafka/journal/JournalPerfSpec.scala
tests/src/test/scala/com/evolutiongaming/kafka/journal/JournalSuite.scala

on receiving records with duplicated `seqNr` from Kafka - take first one 
on receiving records with duplicated `seqNr` from Cassandra - raise error

Reimplement deduplication logic:

---

eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/MigrateSchema.scala
eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/SetupSchema.scala

The idea is to allow several instances to exist, i.e. `SetupJournalSchema` and `SetupSnapshotSchema`.

Extract schema migration into a separate class.

---

eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/CreateKeyspace.scala
eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/KeyspaceConfig.scala
eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/SchemaConfig.scala
eventual-cassandra/src/test/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/CreateSchemaSpec.scala
eventual-cassandra/src/test/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/SchemaConfigSpec.scala
tests/src/test/scala/com/evolutiongaming/kafka/journal/ReadEventsApp.scala

The idea is to allow several instances to exist, i.e. in `CreateJournalSchema` and `CreateSnapshotSchema`.

Extract keyspace configuration to a separate class

---

eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/CassandraSync.scala
eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/SetupSchema.scala

The idea is to allow several instances of `SchemaConfig` to exist, i.e. `JournalSchemaConfig` and `SnapshotSchemaConfig`.

Remove dependency of `CassandraSync` on `SchemaConfig`

---

eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/CassandraConsistencyConfig.scala
eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/CassandraHealthCheck.scala
eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/ConsistencyConfig.scala
eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/EventualCassandra.scala
eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/EventualCassandraConfig.scala
eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/JournalStatements.scala
eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/MetaJournalStatements.scala
eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/Pointer2Statements.scala
eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/PointerStatements.scala
eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/ReplicatedCassandra.scala
eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/SettingStatements.scala
eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/SettingsCassandra.scala
eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/SetupSchema.scala
eventual-cassandra/src/test/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/ConsistencyConfigSpec.scala
eventual-cassandra/src/test/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/EventualCassandraConfigSpec.scala
replicator/src/main/scala/com/evolutiongaming/kafka/journal/replicator/PurgeExpired.scala
tests/src/test/scala/com/evolutiongaming/kafka/journal/SettingsIntSpec.scala

The idea is to refer to it from different configuration case classes, i.e. from `EventualCassandraConfig`, `SnapshotCassandraConfig` and `CassandraHealthCheck`.

Extract consistency settings into a separate class

---

eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/SettingsCassandra.scala
eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/SetupSchema.scala
tests/src/test/scala/com/evolutiongaming/kafka/journal/SettingsIntSpec.scala

The idea is to reuse `SettingsCassandra` in other upcoming modules, i.e. rename `Schema` to `JournalSchema` and then add `SnapshotSchema` for a new snapshotter implementation.

Remove dependency from `SettingsCassandra` to `Schema`

---

journal/src/main/scala/com/evolutiongaming/kafka/journal/Damper.scala
journal/src/test/scala/com/evolutiongaming/kafka/journal/DamperTest.scala

As part of trying to fix `DumperTest` flakiness, I have added some documentation for a `Dumper` class.

Add scaladoc for DamperTest

---

journal/src/main/scala/com/evolutiongaming/kafka/journal/Damper.scala
journal/src/test/scala/com/evolutiongaming/kafka/journal/DamperTest.scala

I wrote a lot of documentation to understand how it works, and debugged it a lot.
It looks like the problem is in the test, which uses `Ref` to specify delays to be used (instead of relying on `acquired` argument).
If the delay between starting two threads is too small then concurrency race happens and `delayOf` function is called twice, when starting `fiber0` and `fiber1`.
I did not convince myself that it is a wrong behavior, so I just increased a delay in the test, so concurrent race does not happen.

Fix the flakiness of DamperTest

---

cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/CassandraHelper.scala
cassandra/src/test/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/CassandraHelperSpec.scala
cassandra/src/test/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/RowStub.scala

This method is required to determine if conditional Cassandra statement was applied. This is needed to have an ability to use lightweight transactions and react on the results of such transactions.
The upcoming https://github.com/evolution-gaming/kafka-journal/milestone/3 milestone needs lightweight transactions to have an ability to rewrite saved snapshots without creating a new row and confirming the snapshot was actually saved.
There is also a single place in existing codebase, where conditional statement is used, but I decided against changing it, for now, to minimize the impact of this PR: https://github.com/evolution-gaming/kafka-journal/blob/1b187462b19298a9b3e595c14ae38cc43010ec87/cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/SettingStatements.scala# …

Add support of #wasApplied method

---

eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/CreateSchema.scala
eventual-cassandra/src/test/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/CreateSchemaSpec.scala

The big idea is to make the class simpler to read and to copy-paste, i.e. rename it to `CreateJournalSchema` and make similar `CreateSnapshotSchema`.
The current approach with functions and code reuse seems to be too complicated for the task.
This PR also simplified `CreateSchemaSpec` by storing created keyspaces and tables instead of artificial `CreateTables` and `CreateKeyspace` actions, and adds a new test case, when some of the tables are created only.
Besides that it adds a new assertion checking that table creation is performed after keyspace creation, and all CQL statements start with `CREATE TABLE IF NOT EXISTS` part with a fully qualified table name.

Simplify CreateSchema class

---

build.sbt

The idea is that `snapshot` module will contain snapshot specific classes and `snapshot-cassandra` will implement these interfaces using Cassandra as a storage backend.
In other words, a new structure will be similar to existing setup, where `journal` and `eventual-cassandra` serve the same purpose.

Add snapshot and snapshot-cassandra sbt modules

---

snapshot/src/main/scala/com/evolutiongaming/kafka/journal/Snapshot.scala

The main question here is if we want to have `payload` as an `Option` or require it always to be filled.
This idea of `Option` was taken from a similar `Event` case class, but I am not sure it applies the same way to a snapshot.

Add a class to pass SeqNr and snapshot payload in

---

snapshot/src/main/scala/com/evolutiongaming/kafka/journal/BufferNr.scala
snapshot/src/test/scala/com/evolutiongaming/kafka/journal/BufferNrSpec.scala

There will be several rows in Cassandra per a single snapshot primary key. Each of these rows will differ by an index, which this class is going to represent.

Add ring buffer index implementation

---

core/src/main/scala/com/evolutiongaming/kafka/journal/Origin.scala
core/src/main/scala/com/evolutiongaming/kafka/journal/Version.scala
snapshot/src/main/scala/com/evolutiongaming/kafka/journal/SnapshotRecord.scala

The idea is to have a class that will be directly mapped to Cassandra columns in a table. The class is inspired by a similar `EventRecord` class. Roughly speaking it is snapshot seqNr/payload + snapshot metadata.
Once again, I am not sure if `version` and `origin` fields should be optional like they are in `EventRecord`.
It may make some sense from uniformity point of view, and for potential ability to save space if there are a lot of snapshots. But I am not sure.

Implement SnapshotRecord class

---

journal/src/main/scala/com/evolutiongaming/kafka/journal/eventual/ReplicatedJournal.scala
journal/src/main/scala/com/evolutiongaming/kafka/journal/eventual/ReplicatedJournalFlat.scala

The reason for the new scaladoc, is that I keep forgetting if it is a write or read part of a journal, and if it gets written to Kafka or Cassandra, and I have to double check every time.
An additional consideration was to understand if I need to name a new snapshotter interface similar to `ReplicatedJournalFlat`, i.e. `SnapshotStorageFlat` or not.

Add scaladoc for ReplicatedJournal

---

snapshot/src/main/scala/com/evolutiongaming/kafka/journal/SnapshotSelectionCriteria.scala
snapshot/src/main/scala/com/evolutiongaming/kafka/journal/SnapshotStore.scala
snapshot/src/main/scala/com/evolutiongaming/kafka/journal/SnapshotStoreFlat.scala

This is intended to be a main entry point to a new snapshotter.
The main considerations were to keep it recognizable and easy to use from a Akka Persistence Plugin, while having no dependencies on Akka itself.
I also tried to make it look similar to `ReplicatedJournalFlat` and `EventualJournal` for sake of uniformity of the codebase.
See also https://github.com/evolution-gaming/kafka-journal/pull/532/files#r1412205449 for a comment from @t3hnar

Add SnapshotStoreFlat interface

---

journal/src/main/scala/com/evolutiongaming/kafka/journal/PayloadAndType.scala
persistence/src/main/scala/akka/persistence/kafka/journal/EventSerializer.scala
persistence/src/main/scala/akka/persistence/kafka/journal/SerializedMsgSerializer.scala

This improves documentation of `PersistentRepresentation` and related classes.
The logic was reverse engineered from https://github.com/evolution-gaming/kafka-journal/pull/144
CC: @ellentari

Add scaladoc for PersistentRepresentation

---

build.sbt
project/plugins.sbt

This PR integrates  `sbt-version-policy` into a build process.
One can now run `sbt versionPolicyCheck` to validate if the upcoming version (3.3.9 at the the time of writing) is binary compatible with the previous one.
That task will fail, because the version is not backwards compatible at the moment of writing. That why the task is not integrated to CI yet.
The version is made compatible in https://github.com/evolution-gaming/kafka-journal/pull/586, which will be split to smaller PRs for an easier review (this is the first such a smaller PR).
I had to update `build.sbt` with a temporary hack which creates a separate `mima-classes` directory for journal and `eventual-cassandra` modules to make sure that `core` and `cassandra` module classes are included as in 3.3.8 version these classes …

Add `sbt-version-policy` to check for backwards compatibility issues

---

eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/CreateSchema.scala
eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/SchemaConfig.scala
eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/SetupSchema.scala
eventual-cassandra/src/test/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/CreateSchemaSpec.scala
eventual-cassandra/src/test/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/SchemaConfigSpec.scala
tests/src/test/scala/com/evolutiongaming/kafka/journal/ReadEventsApp.scala

The idea is to restore binary backwards compatibility of `SchemaConfig`.
`SchemaConfig.Keyspace` is restored for that purposes and the method is added to convert it to `KeyspaceConfig`.
The class itself is marked as deprecated and is planned to be removed in a next non-binary-compatible release.
This is a smaller PR split from #586 for easier review.

Restore binary backwards compatibility of SchemaConfig

---

cassandra/src/main/scala/com/evolutiongaming/kafka/journal/cassandra/CreateKeyspace.scala
eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/CreateKeyspace.scala
eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/CreateSchema.scala
eventual-cassandra/src/test/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/CreateSchemaSpec.scala

There are now two `CreateKeyspace` classes. One in `cassandra` package and one in `eventual.cassandra` package.
See the reasoning behind the approach in the following PR: #594

Restore binary backwards compatibility for CreateKeyspace

---

.github/workflows/ci.yml

This is _almost_ a final PR from https://github.com/evolution-gaming/kafka-journal/pull/586 series. It will enable checking binary compatibility during a CI build process.
There will be couple of PRs more, to clean up the things and fix a bug in a test, though. See https://github.com/evolution-gaming/kafka-journal/milestone/5 for more details.

Enable binary compatibility check in CI

---

core/src/main/scala/com/evolutiongaming/kafka/journal/Settings.scala
tests/src/test/scala/com/evolutiongaming/kafka/journal/SettingsIntSpec.scala

This PR deprecates `setIfEmpty` method as it unreliable and is not used anymore. It is deprecated rather than removed, because API is public and it does not seem to be a good idea to break a binary API in a minor version release.
See #603 for more details.

Fixes #603, deprecate unreliable method, fix flaky test

---

cassandra/src/main/scala/com/evolutiongaming/kafka/journal/cassandra/MigrateSchema.scala
eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/CreateSchema.scala
eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/SetupSchema.scala

This is a new class, common to the eventual Cassandra journal storage and to a new snapshotter, so it does not make sense to keep it in the old path.
To remind: we only kept the classes at this path in `cassandra` sbt subproject for sake of binary compatibility with a previous version.
See https://github.com/evolution-gaming/kafka-journal/pull/594 and https://github.com/evolution-gaming/kafka-journal/pull/586 fore the reasons of such a movement.

Move `MigrateSchema` from `eventual.cassandra` to `cassandra`

---

journal/src/test/scala/com/evolutiongaming/kafka/journal/DamperTest.scala

The original fix made in #555 fixed the original source of flakiness, but introduced a different one by an assertion added to a wrong place. It would check if `delayOf` was called only once, while starting the threads, when cancelation was already started.
The fiber cancelation would also call `delayOf` in a background, and the test would fail from time to time depending on how quickly this call propagates to a `ref` used in a test.

Fixed flakiness of DamperTest again

---

build.sbt
eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/Pointer2Statements.scala
eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/ReplicatedCassandra.scala
journal/src/main/scala/com/evolutiongaming/kafka/journal/eventual/ReplicatedJournal.scala

Expose new temporary metrics when `pointer` table is used as fallback 

---

build.sbt
eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/EventualCassandra.scala
eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/JournalHead.scala
eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/JournalStatements.scala
eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/MetaJournalStatements.scala
eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/RecordId.scala
eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/ReplicatedCassandra.scala
eventual-cassandra/src/main/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/SetupSchema.scala
eventual-cassandra/src/test/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/EventualCassandraSpec.scala
eventual-cassandra/src/test/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/EventualCassandraTest.scala
eventual-cassandra/src/test/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/ReplicatedCassandraTest.scala
eventual-cassandra/src/test/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/SetupSchemaSpec.scala
journal/src/main/scala/com/evolutiongaming/kafka/journal/Journal.scala
persistence/src/test/resources/akka/persistence/kafka/journal/kafka-journal.conf
persistence/src/test/scala/akka/persistence/kafka/journal/KafkaJournalConfigSpec.scala
version.sbt

KJ can be in inconsistent state when (after purging) meta from `metajournal` was deleted while events from `journal` left behind. By itself its not an issue, but after the journal used again and new meta inserted - then old events will be available (probably with duplicated `seqNr`).
Create correlation between meta and events that belong to it, i. e. were created while the meta was present. Then, on reading journal, only events that correlate with meta must be used.
Add `meta_record_id` column to `journal` and `record_id` column to `metajournal` tables. In appending events `RecordId` from meta will be used (if meta has it) and if meta is not present yet - new `RecordId` generated. On reading compare `RecordId` from meta and event ignoring events with another value. `RecordId` is optional …

Add meta_record_id into journal & record_id metajournal tables for gaining correlation between them

---

replicator/src/main/scala/com/evolutiongaming/kafka/journal/replicator/ReplicateRecords.scala
replicator/src/main/scala/com/evolutiongaming/kafka/journal/replicator/TopicReplicatorMetrics.scala
replicator/src/test/scala/com/evolutiongaming/kafka/journal/replicator/TopicReplicatorSpec.scala

Currently there is no easy way to observer what expirations are used by different clients - only options are:
* peek at Kafka messages
* crawl the `journal` table
* search in source
With this change, `replicator` will expose new metric `*_kafka_journal_client_journal_expiration_info` which will expose [a sample] of expirations as observed in replicated data.

expose observed journal expirations as metrics

---

eventual-cassandra/src/test/scala/com/evolutiongaming/kafka/journal/eventual/cassandra/ReplicatedCassandraTest.scala
replicator/src/main/scala/com/evolutiongaming/kafka/journal/replicator/Batch.scala
replicator/src/test/scala/com/evolutiongaming/kafka/journal/replicator/BatchSpec.scala

We optimize actions to reduce load on Cassandra when in single poll we get actions like:
* append @ 5
* append @ 6
* delete till 6
Optimization removed previous append actions, when `delete` would remove them after insertion.
The optimization keeps the `journal` table in shape, but it fails to update `metajournal` table, like when:
* `metajournal` table has entry with `deleteTo: 4; seqNr: 4`
* after receiving above-mentioned batch, we update `deleteTo` to `4` and `seqNr` stays as it was
* result is that we have `deleteTo: 4; seqNr: 4` (as `DeleteTo` got clamped down to existing `seqNr` to not overshoot future events in journal) - we lost updates: `seqNr: 6` and didn't update `deleteTo: 6`
This happens rarely, usually when client is quiet for some time and then issues "closing" statements. …

optimization of `append + delete` actions leads to inconsistent state in metajournal table

---

journal/src/main/scala/com/evolutiongaming/kafka/journal/HeadInfo.scala
persistence/src/main/scala/akka/persistence/kafka/journal/PersistentBinary.scala

- PersistentBinary should be public because PersistentJson is
- HeadInfo should be public because HeadCache interface is public, and it can't be implemented because HeadInfo is currently private

Revert some visibility changes

---

journal/src/main/scala/com/evolutiongaming/kafka/journal/ConsumerPool.scala
journal/src/main/scala/com/evolutiongaming/kafka/journal/Journal.scala
persistence/src/main/resources/reference.conf

- without it, if clients tried to partially override an option inside a nested section, it failed at runtime:
```
pureconfig.error.ConfigReaderException: Cannot convert configuration to a scala.runtime.Nothing$. Failures are:
at 'data-integrity':
- (deployments/common/persistence.conf @ file:/Users/msokolov/prog/evo/rbow/betting/target/scala-2.13/classes/deployments/common/persistence.conf: 318) Key not found: 'correlate-events-with-meta'.
```
- added docs to config options
- fixed ConsumerPool max size potentially going below 1

Add missing default config options in plugin's reference.conf

---

replicator/src/main/scala/com/evolutiongaming/kafka/journal/replicator/ReplicatedOffsetNotifier.scala
replicator/src/main/scala/com/evolutiongaming/kafka/journal/replicator/Replicator.scala
replicator/src/main/scala/com/evolutiongaming/kafka/journal/replicator/TopicReplicator.scala
replicator/src/test/scala/com/evolutiongaming/kafka/journal/replicator/TopicReplicatorSpec.scala

Current recovery logic doesn't scale when the volume of events is large, because clients have to consume all the events on all the app nodes. Additionally, current logic creates Kafka consumers on-demand, which is a heavy operation. This consumer creation happens in spikes, when replicator is running late, and affects client applications stability.
Introducing a side channel for notifications about replication progress will allow us in the future to have an alternative implementation for recovery without these flaws. I.e. notifications go to a separate lean Kafka topic which is read by all client nodes. On recovery:
- a mark is written
- wait until mark offset confirmed replicated in the notification topic (with potential fallback to polling of the pointer table in Cassandra)
- recover …

Add ReplicatedOffsetNotifier callback

---

replicator/src/main/resources/reference.conf
replicator/src/main/scala/com/evolutiongaming/kafka/journal/replicator/ReplicatorConfig.scala

Use CooperativeStickyAssignor in replicator Kafka consumers
to potentially reduce peak tail replication latency during replicator redeployments

Use CooperativeStickyAssignor in replicator Kafka consumers

---

build.sbt
project/Dependencies.scala
tests/src/test/scala/com/evolutiongaming/kafka/journal/IntegrationSuite.scala

This will come in handy when we migrate to Scala 3:
- kafka-launcher starts Kafka in the same JVM and classpath as the KJ code, so we are tied to Kafka server's own Scala version support
- testcontainers Kafka starts in Docker, thus we are not tied anymore
Additionally:
- migrated from a Scala wrapper to using testcontainers directly - this way we can use the latest testcontainers version
- now Kafka and Cassandra start in parallel in tests
- test Cassandra and Kafka versions are now set explicitly

Replace kafka-launcher with testcontainers-kafka

---

build.sbt
journal/src/main/scala/com/evolutiongaming/kafka/journal/KafkaConsumer.scala
project/Dependencies.scala
replicator/src/main/scala/com/evolutiongaming/kafka/journal/replicator/ConsumeTopic.scala
replicator/src/main/scala/com/evolutiongaming/kafka/journal/replicator/TopicCommit.scala
replicator/src/main/scala/com/evolutiongaming/kafka/journal/replicator/TopicReplicator.scala
replicator/src/main/scala/com/evolutiongaming/kafka/journal/replicator/commit/AsyncPeriodicTopicCommit.scala
replicator/src/test/scala/com/evolutiongaming/kafka/journal/replicator/ConsumeTopicTest.scala
replicator/src/test/scala/com/evolutiongaming/kafka/journal/replicator/DelayedTopicCommitTest.scala
replicator/src/test/scala/com/evolutiongaming/kafka/journal/replicator/DistributeJobTest.scala
replicator/src/test/scala/com/evolutiongaming/kafka/journal/replicator/EmptyRebalanceConsumer.scala
replicator/src/test/scala/com/evolutiongaming/kafka/journal/replicator/SKafkaTestUtils.scala
replicator/src/test/scala/com/evolutiongaming/kafka/journal/replicator/commit/AsyncPeriodicTopicCommitStateTest.scala
replicator/src/test/scala/com/evolutiongaming/kafka/journal/replicator/commit/AsyncPeriodicTopicCommitTest.scala

The next release version should have a minor increment - 4.2.0
- TopicCommit.apply renamed to TopicCommit.sync, TopicCommit.apply deprecated
- Added TopicCommit.asyncPeriodic implementation
- TopicCommit.delayed deprecated in favor of TopicCommit.asyncPeriodic
- TopicCommit.asyncPeriodic is used by default in the replicator
- updated skafka for an async commit method fix
Main features of asyncPeriodic:
- periodic commits are done asynchronously without blocking the main poll loop, improving latency
- it properly handles rebalance, not loosing progress for revoked partitions
- same logic commits offsets on app shutdown because Java consumer invokes revoke partition callbacks on closure
- gracefully handles RebalanceInProgressException
Additionally:
- made TopicCommit journal package …

New improved Kafka offset commit logic for replicator

---

build.sbt
journal/src/main/scala/com/evolutiongaming/kafka/journal/HeadCache.scala
journal/src/main/scala/com/evolutiongaming/kafka/journal/PartitionCache.scala
journal/src/main/scala/com/evolutiongaming/kafka/journal/TopicCache.scala

Remove type arg variance in PartitionCache.Result
as it trips out Scala 3 compiler in pattern-matching. Also having variance for F[_]-kind of type args
doesn't look right.

Prepare for Scala 3 support - more code changes

---

build.sbt
project/Dependencies.scala

Updated almost all dependencies to versions having Scala 3 cross-compilation. The only one missing is scodec for which we would need to have different versions for Scala 2.13 and Scala 3.

Prepare for Scala 3 support - update dependencies
